name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        id: set_version
        run: |
          # 태그가 있으면 태그를, 없으면 short commit hash 사용
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Sublime Package
        run: |
          # 패키지 디렉토리 생성
          mkdir -p build
          
          # 필요한 파일들 복사
          cp __init__.py build/
          cp sqlvariablesconverter.py build/
          cp Default.sublime-commands build/
          cp .no-sublime-package build/
          cp package-metadata.json build/
          
          # Sublime Package 생성
          cd build
          zip -r ../SqlVariablesConverter.sublime-package *
          cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: SqlVariablesConverter ${{ env.VERSION }}
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || format('release-{0}', env.VERSION) }}
          files: SqlVariablesConverter.sublime-package
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 